// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{
    type: 'autogenerated',
    dirName: '.',
  }],

  //  A more customised sidebar.
  anotherSidebar: [
    'index',
    {
      type: 'category',
      label: 'Transitioning to the Shell',
      link: { type: 'doc', id: 'transitioning-to-the-shell/index'},
      items: [
        'transitioning-to-the-shell/getting-started/01-getting-started',
        'transitioning-to-the-shell/navigating-your-system/02-navigating-your-system',
        'transitioning-to-the-shell/managing-your-files/03-managing-your-files',
        'transitioning-to-the-shell/clipboard-gymnastics/04-become-a-clipboard-gymnast',
        'transitioning-to-the-shell/getting-help/05-getting-help',
        'transitioning-to-the-shell/the-renaissance-of-the-shell/06-the-renaissance-of-the-shell',
      ]
    },
  ],
};

module.exports = sidebars;
