module.exports = {
  docs: [
    {
      type: 'doc',
      id: 'index',
    },
    {
      type: 'doc',
      id: 'introduction/index',
    },
    {
      type: 'doc',
      id: 'getting-started/index',
    },
    {
      type: 'category',
      label: 'Docs',
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs',
        },
      ],
    },
  ],
}
